project_id = "oiarehtqhgwkiunsarmz"

[functions.parse-ticket]
verify_jwt = false

[functions.create-setup-intent]
verify_jwt = false

[functions.verify-id]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.check-fraud]
verify_jwt = false

[functions.verify-voucher]
verify_jwt = false
