export type Locale = "en" | "it";

export const copy = {
  en: {
    s1_eyebrow: "1. Upload your ticket",
    s1_title: "Drag in your PDF",
    s1_filename: "british_airways_BA478.pdf",
    s2_eyebrow: "2. We fill it in",
    s2_title: "Auto-filled from PDF",
    s2_route: "London (LHR) → Barcelona (BCN)",
    s2_date: "Sat 6 Jun · 09:25 · BA478",
    s2_paid: "Original price £142",
    s3_eyebrow: "3. Boost & publish",
    s3_boost: "Boost visibility",
    s3_publish: "Publish listing",
    s4_eyebrow: "4. Buyer side",
    s4_title: "Ask in plain English",
    s4_query: "Weekend trip from London",
    s4_chip: "AI search",
    s5_eyebrow: "5. Smart matches",
    s5_title: "3 perfect seats",
    s5_cards: [
      { route: "LHR → BCN", date: "Sat 6 Jun", price: "£68", was: "£142" },
      { route: "LGW → LIS", date: "Fri 5 Jun", price: "£54", was: "£119" },
      { route: "STN → BUD", date: "Sat 6 Jun", price: "£39", was: "£88" },
    ],
    s6_eyebrow: "6. Done",
    s6_title: "Ticket transferred",
    s6_sub: "+ £68.00 paid out",
    s6_notif: "Name change confirmed · payout released",
    outro1: "List. Match. Get paid.",
    outro2: "Swappup",
  },
  it: {
    s1_eyebrow: "1. Carica il biglietto",
    s1_title: "Trascina qui il PDF",
    s1_filename: "vueling_VY6321.pdf",
    s2_eyebrow: "2. Compiliamo noi",
    s2_title: "Compilato dal PDF",
    s2_route: "Milano (MXP) → Barcellona (BCN)",
    s2_date: "Sab 6 giu · 09:25 · VY6321",
    s2_paid: "Prezzo originale €148",
    s3_eyebrow: "3. Aumenta visibilità & pubblica",
    s3_boost: "Aumenta visibilità",
    s3_publish: "Pubblica annuncio",
    s4_eyebrow: "4. Lato acquirente",
    s4_title: "Chiedi in linguaggio naturale",
    s4_query: "Weekend da Milano",
    s4_chip: "Ricerca AI",
    s5_eyebrow: "5. Risultati intelligenti",
    s5_title: "3 posti perfetti",
    s5_cards: [
      { route: "MXP → BCN", date: "Sab 6 giu", price: "€72", was: "€148" },
      { route: "LIN → LIS", date: "Ven 5 giu", price: "€89", was: "€164" },
      { route: "BGY → BUD", date: "Sab 6 giu", price: "€44", was: "€96" },
    ],
    s6_eyebrow: "6. Fatto",
    s6_title: "Biglietto trasferito",
    s6_sub: "+ €72,00 accreditati",
    s6_notif: "Cambio nome confermato · pagamento sbloccato",
    outro1: "Pubblica. Vendi. Incassa.",
    outro2: "Swappup",
  },
} as const;