export type Locale = "en" | "it";

export const copy = {
  en: {
    s1_eyebrow: "1. Upload your ticket",
    s1_title: "Drag in your ticket confirmation",
    s1_filename: "british_airways_BA478.pdf",
    s2_eyebrow: "2. We fill it in",
    s2_title: "Auto-filled in a few seconds",
    s2_fields: [
      { label: "From", value: "London (LHR)" },
      { label: "To", value: "Barcelona (BCN)" },
      { label: "Date", value: "Sat 6 Jun · 09:25" },
      { label: "Flight", value: "BA478" },
      { label: "Airline", value: "British Airways" },
      { label: "Original price", value: "£142" },
    ],
    s3_eyebrow: "3. Boost & publish",
    s3_title: "Put your listing under the spotlight",
    s3_boost: "Boost visibility",
    s3_publish: "Publish listing",
    s4_eyebrow: "4. Search for your next adventure",
    s4_title: "Look for a ticket deal",
    s4_query: "Weekend trip from London",
    s4_chip: "AI search",
    s5_eyebrow: "5. Select your trip",
    s5_title: "Choose and pay safely in a few clicks",
    s5_cards: [
      { route: "London → Barcelona", date: "Sat 6 Jun", price: "£68", city: "Barcelona", hue: 18 },
      { route: "London → Lisbon", date: "Fri 5 Jun", price: "£54", city: "Lisbon", hue: 200 },
      { route: "London → Budapest", date: "Sat 6 Jun", price: "£39", city: "Budapest", hue: 280 },
    ],
    s6_eyebrow: "6. Ticket transferred",
    s6_title: "Get ready to travel!",
    s6_sub: "+ £68.00 paid out",
    s6_notif: "Name change confirmed · payout released",
    outro1: "List. Match. Get paid.",
    outro2: "Swappup",
  },
  it: {
    s1_eyebrow: "1. Carica il biglietto",
    s1_title: "Trascina la conferma del biglietto",
    s1_filename: "vueling_VY6321.pdf",
    s2_eyebrow: "2. Compiliamo noi",
    s2_title: "Compilato in pochi secondi",
    s2_fields: [
      { label: "Da", value: "Milano (MXP)" },
      { label: "A", value: "Barcellona (BCN)" },
      { label: "Data", value: "Sab 6 giu · 09:25" },
      { label: "Volo", value: "VY6321" },
      { label: "Compagnia", value: "Vueling" },
      { label: "Prezzo originale", value: "€148" },
    ],
    s3_eyebrow: "3. Aumenta visibilità & pubblica",
    s3_title: "Metti il tuo annuncio in vetrina",
    s3_boost: "Aumenta visibilità",
    s3_publish: "Pubblica annuncio",
    s4_eyebrow: "4. Cerca la tua prossima avventura",
    s4_title: "Trova l'offerta giusta",
    s4_query: "Weekend da Milano",
    s4_chip: "Ricerca AI",
    s5_eyebrow: "5. Scegli il tuo viaggio",
    s5_title: "Scegli e paga in sicurezza in pochi clic",
    s5_cards: [
      { route: "Milano → Barcellona", date: "Sab 6 giu", price: "€72", city: "Barcellona", hue: 18 },
      { route: "Milano → Lisbona", date: "Ven 5 giu", price: "€89", city: "Lisbona", hue: 200 },
      { route: "Milano → Budapest", date: "Sab 6 giu", price: "€44", city: "Budapest", hue: 280 },
    ],
    s6_eyebrow: "6. Biglietto trasferito",
    s6_title: "Preparati a partire!",
    s6_sub: "+ €72,00 accreditati",
    s6_notif: "Cambio nome confermato · pagamento sbloccato",
    outro1: "Pubblica. Vendi. Incassa.",
    outro2: "Swappup",
  },
} as const;