export type Locale = "en" | "it";

export const copy = {
  en: {
    s1_eyebrow: "Sell a ticket",
    s1_title: "Upload your ticket confirmation",
    s1_screen: "Sell Your Ticket",
    s1_ticket_passenger: "John Smith",
    s1_ticket_flight: "EZY8521",
    s1_ticket_from: "LGW",
    s1_ticket_to: "BCN",
    s1_ticket_fromCity: "London",
    s1_ticket_toCity: "Barcelona",
    s1_ticket_date: "06 JUN",
    s1_ticket_gate: "A12",
    s1_ticket_seat: "14C",
    s1_ticket_airline: "easyJet",
    s2_eyebrow: "Auto-filled in a few seconds",
    s2_title: "Verify your ticket details",
    s2_screen: "Sell Your Ticket",
    s2_cta: "Next",
    s2_fields: [
      { label: "From", value: "London (LGW)" },
      { label: "To", value: "Barcelona (BCN)" },
      { label: "Date", value: "Sat 6 Jun · 09:25" },
      { label: "Flight", value: "EZY8521" },
      { label: "Airline", value: "easyJet" },
      { label: "Original price", value: "£142" },
      { label: "Listing price", value: "£89" },
    ],
    s3_eyebrow: "Boost your listing",
    s3_title: "Publish your listing",
    s3_screen: "Sell Your Ticket",
    s3_boost: "Boost visibility",
    s3_publish: "Publish listing",
    s3_boost_options: [
      { label: "24 hours", price: "€1.99" },
      { label: "3 days", price: "€3.99" },
      { label: "7 days", price: "€4.99" },
    ],
    s4_eyebrow: "Search for your next adventure",
    s4_title: "Look for a ticket deal",
    s4_screen: "Search",
    s4_query: "Weekend trip from London",
    s4_chip: "AI search",
    s5_eyebrow: "Select your trip",
    s5_title: "Choose and pay safely in a few clicks",
    s5_screen: "Search",
    s5_cards: [
      { route: "London → Barcelona", date: "Sat 6 Jun", price: "£68", airline: "easyJet", image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&auto=format&fit=crop" },
      { route: "London → Lisbon", date: "Fri 5 Jun", price: "£54", airline: "Vueling", image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&auto=format&fit=crop" },
      { route: "London → Budapest", date: "Sat 6 Jun", price: "£39", airline: "Ryanair", image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=600&auto=format&fit=crop" },
    ],
    s6_eyebrow: "Ticket transferred",
    s6_title: "Get ready to travel!",
    s6_screen: "Swappup",
    s6_sub: "+ £68.00 paid out",
    s6_notif: "Name change confirmed · payout released",
    outro1: "List. Match. Get paid.",
    outro2: "Swappup",
  },
  it: {
    s1_eyebrow: "Vendi un biglietto",
    s1_title: "Carica la conferma del biglietto",
    s1_screen: "Vendi il tuo biglietto",
    s1_ticket_passenger: "Marco Rossi",
    s1_ticket_flight: "VY6321",
    s1_ticket_from: "MXP",
    s1_ticket_to: "BCN",
    s1_ticket_fromCity: "Milano",
    s1_ticket_toCity: "Barcellona",
    s1_ticket_date: "06 GIU",
    s1_ticket_gate: "A12",
    s1_ticket_seat: "14C",
    s1_ticket_airline: "Vueling",
    s2_eyebrow: "Compilato in pochi secondi",
    s2_title: "Verifica i dettagli del biglietto",
    s2_screen: "Vendi il tuo biglietto",
    s2_cta: "Avanti",
    s2_fields: [
      { label: "Da", value: "Milano (MXP)" },
      { label: "A", value: "Barcellona (BCN)" },
      { label: "Data", value: "Sab 6 giu · 09:25" },
      { label: "Volo", value: "VY6321" },
      { label: "Compagnia", value: "Vueling" },
      { label: "Prezzo originale", value: "€148" },
      { label: "Prezzo di vendita", value: "€95" },
    ],
    s3_eyebrow: "Aumenta la visibilità",
    s3_title: "Pubblica il tuo annuncio",
    s3_screen: "Vendi il tuo biglietto",
    s3_boost: "Aumenta visibilità",
    s3_publish: "Pubblica annuncio",
    s3_boost_options: [
      { label: "24 ore", price: "€1,99" },
      { label: "3 giorni", price: "€3,99" },
      { label: "7 giorni", price: "€4,99" },
    ],
    s4_eyebrow: "Cerca la tua prossima avventura",
    s4_title: "Trova l'offerta giusta",
    s4_screen: "Cerca",
    s4_query: "Weekend da Milano",
    s4_chip: "Ricerca AI",
    s5_eyebrow: "Scegli il tuo viaggio",
    s5_title: "Scegli e paga in sicurezza in pochi clic",
    s5_screen: "Cerca",
    s5_cards: [
      { route: "Milano → Barcellona", date: "Sab 6 giu", price: "€72", airline: "Vueling", image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&auto=format&fit=crop" },
      { route: "Milano → Lisbona", date: "Ven 5 giu", price: "€89", airline: "Ryanair", image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&auto=format&fit=crop" },
      { route: "Milano → Budapest", date: "Sab 6 giu", price: "€44", airline: "Wizz Air", image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=600&auto=format&fit=crop" },
    ],
    s6_eyebrow: "Biglietto trasferito",
    s6_title: "Preparati a partire!",
    s6_screen: "Swappup",
    s6_sub: "+ €72,00 accreditati",
    s6_notif: "Cambio nome confermato · pagamento sbloccato",
    outro1: "Pubblica. Vendi. Incassa.",
    outro2: "Swappup",
  },
} as const;